export const SHOW_EXERCISES = "SHOW_EXERCISES";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const EDIT_EXERCISE = "EDIT_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
export const SHOW_MUSCLES = "SHOW_MUSCLES";
